# Azure Pipeline for Terraform Deployment
# Author: Nigel P


trigger: none

pool: ubuntulatest

variables:
- group: TF_SERVICE_PRINCIPAL
- group: TF_BACKEND_CONFIG

stages:
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      - task: TerraformCLI@0
        displayName: 'terraform init'
        inputs:
          command: 'init'
          backendType: azurerm
          ensureBackend: true
          backendAzureRmResourceGroupName:  $(aps-resource-group-name)
          backendAzureRmContainerName:      $(aps-container-name)
          backendAzureRmStorageAccountName: $(aps-storage-account-name)
          backendAzureRmKey:                $(aps-key)
          allowTelemetryCollection: true
          commandOptions:  '-var ARM_CLIENT_ID        = $(aps-arm-client-id)      \
                            -var ARM_CLIENT_SECRET    = $(aps-arm-client-secret)  \
                            -var ARM_SUBSCRIPTION_ID  = ${aps-subscription-id}    \
                            -var ARM_TENANT_ID        = $(aps-tenant-id)'

