# Azure Pipeline for Terraform Deployment
# Author: Nigel P
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: ubuntulatest

stages:
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      - task: TerraformCLI@0
        displayName: 'terraform init'
        env:
          ARM_SUBSCRIPTION_ID: ${aps}
        inputs:
          command: 'init'
          backendType: azurerm
          ensureBackend: true
          backendAzureRmResourceGroupName: 
          allowTelemetryCollection: true

