# Azure Pipeline for Terraform Deployment
# Author: Nigel P


trigger: none

pool: 
  vmImage: 'ubuntu-latest'

variables:
- group: TF_SERVICE_PRINCIPAL
- group: TF_BACKEND_CONFIG



stages:
  - stage: validate

    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      - task: DownloadSecureFile@1
        name: tfPublicKey
        inputs:
          secureFile: 'tfkey.pub'
          socketTimeout: '30000'
          retryCount: 8

      - task: DownloadSecureFile@1
        name: tfVarsFile
        displayName: 'Download Terraform input variables file'
        inputs:
          secureFile: 'terraform.tfvars'
          socketTimeout: '30000'
          retryCount: 8
      - task: TerraformCLI@0
        displayName: 'terraform init'
        env:
            TF_APS_RESOURCE_GROUP_NAME    : $(aps-resource-group-name)
            TF_APS_RESOURCE_CONTAINER_NAME: $(aps-container-name)
            TF_APS_STORAGE_ACCOUNT_NAME   : $(aps-storage-account-name)
            TF_APS_KEY                    : $(aps-key)
            TF_ARM_CLIENT_ID              : $(aps-arm-client-id)
            TF_ARM_CLIENT_SECRET          : $(aps-arm-client-secret)
            TF_ARM_SUBSCRIPTION_ID        : $(aps-subscription-id)
            TF_ARM_TENANT_ID              : $(aps-tenant-id)
        inputs:
          command: 'init'
          allowTelemetryCollection: true
          backendType: azurerm
          backendServiceArm: 'Azure subscription 1(fd267d27-d3b1-4597-81dc-e98d71ee70de)'
          backendAzureRmStorageAccountName: '$(aps-storage-account-name)'
          backendAzureRmContainerName: '$(aps-container-name)'
          backendAzureRmKey: '$(aps-key)'
          backendAzureRmResourceGroupName: '$(aps-resource-group-name)'
          commandOptions:  '-var ARM_CLIENT_ID=$TF_ARM_CLIENT_ID -var ARM_CLIENT_SECRET=$TF_ARM_CLIENT_SECRET -var ARM_SUBSCRIPTION_ID=$TF_ARM_SUBSCRIPTION_ID -var ARM_TENANT_ID=$TF_ARM_TENANT_ID'


      - task: TerraformCLI@0
        displayName: 'terraform validate'
        inputs:
          command: 'validate'
          commandOptions: '-var fileloc=$(tfPublicKey.secureFilePath)'
          allowTelemetryCollection: true
  
  - stage: plan
    dependsOn: [validate]
    condition: succeeded('validate')
    jobs:
      - job: terraform_plan_develop
        steps:
        - task: TerraformInstaller@0
          displayName: Terraform Install
          inputs:
            terraformVersion: 'latest'

        - task: DownloadSecureFile@1
          name: tfVarsFile
          displayName: 'Download Terraform input variables file'
          inputs:
            secureFile: 'terraform.tfvars'
            socketTimeout: '30000'
            retryCount: 8

        - script: |
            echo Using $(tfVarsFile.secureFilePath) as Terraform input....

        - task: TerraformCLI@0
          displayName: 'terraform plan'
          env:
            TF_APS_RESOURCE_GROUP_NAME    : $(aps-resource-group-name)
            TF_APS_RESOURCE_CONTAINER_NAME: $(aps-container-name)
            TF_APS_STORAGE_ACCOUNT_NAME   : $(aps-storage-account-name)
            TF_APS_KEY                    : $(aps-key)
            TF_ARM_CLIENT_ID              : $(aps-arm-client-id)
            TF_ARM_CLIENT_SECRET          : $(aps-arm-client-secret)
            TF_ARM_SUBSCRIPTION_ID        : $(aps-subscription-id)
            TF_ARM_TENANT_ID              : $(aps-tenant-id)
          inputs:
            command: 'plan'
            backendType: azurerm
            ensureBackend: true
            backendAzureRmResourceGroupName:  $TF_APS_RESOURCE_GROUP_NAME
            backendAzureRmContainerName:      $TF_APS_RESOURCE_CONTAINER_NAME
            backendAzureRmStorageAccountName: $TF_APS_STORAGE_ACCOUNT_NAME
            backendAzureRmKey:                $TF_APS_KEY
            allowTelemetryCollection:         true
            commandOptions:  '-input=true                                               \
                              -out=$(System.DefaultWorkingDirectory)/terraform.tfplan   \
                              -detailed-exitcode                                        \
                              -var ARM_CLIENT_ID=$TF_ARM_CLIENT_ID         \
                              -var ARM_CLIENT_SECRET=$TF_ARM_CLIENT_SECRET     \
                              -var ARM_SUBSCRIPTION_ID=$TF_ARM_SUBSCRIPTION_ID   \
                              -var ARM_TENANT_ID=$TF_ARM_TENANT_ID         \
                              -var-file=$(tfVarsFile.secureFilePath)  \'